# MIT License
# Copyright (c) 2021-2024, Neville Studio.
# 
# (for China)软件著作权登记证号：2024SR0209367
# 
# Thanks Github Copilot for the help with this file!
# 感谢 Github Copilot 帮助我编写这个文件！
# This file helps github to build and release the NetTimeSyncTool. The executable will no longer 
# be built locally, but on Github.
# 这个文件帮助 Github 编译和发布 NetTimeSyncTool。可执行文件将不再在本地构建，而是在 Github 上构建。


name: Release

on:
  create:
    tags:
      - 'v*'
env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: write
  packages: write
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Restore NuGet packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: nuget restore ${{env.SOLUTION_FILE_PATH}}

      - name: Build x64
        run: msbuild /p:Configuration=Release /p:Platform=x64 NetTimeSyncTool.sln

      - name: Upload x64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: x64-artifact
          path: ./x64/Release/NetTimeSyncTool.exe

      - name: Build x86
        run: msbuild /p:Configuration=Release /p:Platform=x86 NetTimeSyncTool.sln

      - name: Upload x86 artifact
        uses: actions/upload-artifact@v4
        with:
          name: x86-artifact
          path: ./Release/NetTimeSyncTool.exe

      - name: Build ARM64
        run: msbuild /p:Configuration=Release /p:Platform=ARM64 NetTimeSyncTool.sln

      - name: Upload ARM64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: x86-artifact
          path: ./ARM64/Release/NetTimeSyncTool.exe

  release:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Download x64 artifact
        uses: actions/download-artifact@v4
        with:
          name: x64-artifact
          path: ${{ github.workspace }}/x64/Release/

      - name: Download x86 artifact
        uses: actions/download-artifact@v4
        with:
          name: x86-artifact
          path: ${{ github.workspace }}/Release/
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: NetTimeSyncTool-${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload x64 Executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./x64/Release/NetTimeSyncTool.exe
          asset_name: NetTimeSyncTool-x64-windows.exe
          asset_content_type: application/octet-stream

      - name: Upload x86 Executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Release/NetTimeSyncTool.exe
          asset_name: NetTimeSyncTool-x86-windows.exe
          asset_content_type: application/octet-stream

      - name: Upload ARM64 Executable
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ARM64/Release/NetTimeSyncTool.exe
          asset_name: NetTimeSyncTool-ARM64-windows.exe
          asset_content_type: application/octet-stream
