name: Release

on:
  create:
    tags:
      - 'v*'
env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Restore NuGet packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: nuget restore ${{env.SOLUTION_FILE_PATH}}

      - name: Build x64
        run: msbuild /p:Configuration=Release /p:Platform=x64 NetTimeSyncTool.sln

      - name: Build x86
        run: msbuild /p:Configuration=Release /p:Platform=x86 NetTimeSyncTool.sln

  release:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:

          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload x64 Executable
        uses: actions/upload-artifact@v2
        with:
          name: x64 Executable
          path: ./x64/Release/NetTimeSyncTool.exe

      - name: Upload x86 Executable
        uses: actions/upload-artifact@v2
        with:
          name: x86 Executable
          path: ./Release/NetTimeSyncTool.exe
